# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-02 22:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20160510_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='printerlog',
            name='counter_duplex',
            field=models.IntegerField(default=0),
        ),
    ]
