# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-19 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_printerlog_counter_duplex'),
    ]

    operations = [
        migrations.AddField(
            model_name='printerlog',
            name='coordinate_X',
            field=models.FloatField(default=28.698494),
        ),
        migrations.AddField(
            model_name='printerlog',
            name='coordinate_Y',
            field=models.FloatField(default=-106.130584),
        ),
    ]
